name: build
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out source code
        uses: actions/checkout@v1
        with:
          path: go/src/github.com/bokan/facedetection

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
          args: -E golint -E gofmt -E govet -E goimports -E gocyclo -E gocognit -E ineffassign -E misspell

      - name: go test ./...
        env:
          GOPATH: /home/runner/work/facedetection/go
        run: go test ./...

      - name: Docker build
        run: docker build -t facedetection:latest .
